repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest --cov=autogpt --without-integration --without-slow-integration
        language: system
        pass_filenames: false
        always_run: true
